sudo: required

env:
  - DOCKER_HOST=unix:///var/run/docker.sock

services:
  - docker

before_install:
  - make
  - docker build -t  abhijo89/alpine-nginx-php7 .
  - docker ps -a
  


after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";docker push abhijo89/alpine-nginx-php7;
email:
  - ouncebook@gmail.com
