sudo: required

env:
  - DOCKER_HOST=unix:///var/run/docker.sock

services:
  - docker

before_install:
  - docker build -t  abhijo89/alpine-nginx-php7
  - docker ps -a
  


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi
